---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-apps
  namespace: apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
      namespace: flux-system
  path: ./staging
  serviceAccountName: flux-apps
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-apps
  prune: true
  validation: client