apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo-repository.yaml
  - podinfo-release.yaml
  # - secrets.yaml
patches:
  - patch: |-
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
      metadata:
        name: podinfo
        namespace: flux-system
      spec:
        minReplicas: 3             
    target:
      name: podinfo
      kind: HorizontalPodAutoscaler