apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  serviceAccountName: flux-system
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
  values:
    replicaCount: 4
    # ui: 
    # - name: message
    #   valueFrom:
    #     secretKeyRef:
    #       name: podinfo
    #       key: uimessage