apiVersion: v1
kind: Secret
metadata:
    name: podinfo
    namespace: flux-system
stringData:
    uimessage: ENC[AES256_GCM,data:pNTR++eQgbg=,iv:OqFdcfBjA7+6DtgO4nTbZq9NgF0SipbCL8M5F/N4aSc=,tag:U8+Vavrt7373yEVpbcftCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-06T11:18:08Z"
    mac: ENC[AES256_GCM,data:XlZ4LrdqoRKJIkpE9Prvy0d9YG9roj0Jn9qx/kqyJz9sNNxEJupnlKMuPzHKTwEtbits0jkix+s0aDELIYb/yRLCBRpgjmRj9TCLDb+ah+7skz8TuKW7O+H8nKdgR62xiunZ7X1kGNkNFTLpkg1eQUODsIHzWuyqqoB6vqd7TJg=,iv:qMnaO06waCKpoECR/YxCmWpGHVPdzAy5QGys6WRfj8g=,tag:xNO1jyvXkr61S4wmeDvXlQ==,type:str]
    pgp:
        - created_at: "2022-07-06T11:18:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2arRn2AErx8AQ/+OMdG0WuXiA6qnZSDVdg8n8ooFPWePLvxjZqqElhCLwj5
            V/LO82B+0Cxj/nlcKxqAT2Tu25fy0RUW5/uyp/1M2IswQOZ+YqYKIgprnQmQAkai
            NcbS3iiAkv9Q73SdxJYlHTPVEo3ghJ4Exc7nzLIi7OVsAAssV7psxjmDTUC/JMWZ
            l+pxwc6nVYrMhv/EKW5KkXEH/ku7NmdKKF0DTYGRlHhJRzR+OEwQo017W+tYN+QP
            Q8VcaoLWNMxyMNjqw3ucIajF1vWZK6JpmebijSOP2+4D80yRNKVQu6fsBBc/pqE5
            go/B5DQnLDUJ9OTJseH6r/FR94r5k6dZrID96Pc6OI9+ozyznPRqtjIPSfcVPwB6
            oaxNFqZULi4xb5lP510Bp4BsvMWas+uYj/YYr0p6hfgJEcWtFz2ZvuIQhVp9UIVA
            i+aD3xIFD2L14rBMa9UTBMaIxAInkMHQ/SDFE4LxraPmmBR9PRQxwayFarHBoGLv
            6kzHuEOD4Z0VRiaYGA0SgK3CudcArkj+envKcgQwuYuHOGSIZtj5jDGdqW9NUdrV
            axKS2yZib3eAqCW862Y+VleXRgT9uy3ap9MFrO0pzVMNnoPZrj6k2g2mHFkX1ngw
            Wldh6PHF9+i67LBCG2JMNaLigYPI/iKLceATdUED0NwmbpgKC/wjqRI2GCO6furS
            XgGcteVxYtE2zyNp6Q/712b0zhHNwktewudlmPnImR7u26SHA2n5rUZ6rTd/BbWY
            mA8+XWAjJ/xMybrri9TFgI4OELXxTDcexvHxusYY34CRW2eW0p35X29nafhlDHk=
            =gDqG
            -----END PGP MESSAGE-----
          fp: 8613B989B50503317A8888D881647CC9F85E990B
    encrypted_regex: uimessage
    version: 3.7.1
