---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: chartmuseum
      version: "2.14.2"
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      interval: 1m
  values:
    env:
      open:
        AWS_SDK_LOAD_CONFIG: true
        STORAGE: amazon
        STORAGE_AMAZON_BUCKET: "lifebit-helm-repository"
        STORAGE_AMAZON_PREFIX: ""
        STORAGE_AMAZON_REGION: "eu-west-1"
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::160259387244:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/23E7738ED0291A742819BBE7BD6241E2"
    securityContext:
      enabled: true
      fsGroup: 65534

# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: helm-charts
#   namespace: flux-system
# spec:
#   interval: 1m
#   url: http://chartmuseum-chartmuseum:8080