---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-external

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-external
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.1.4'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-external
      interval: 100m
  values:
    replicaCount: 2