---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-external

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-external
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.1.4'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-external
      interval: 100m
  values:
    controller:
    
      ingressClassResource:
        # -- Name of the ingressClass
        name: nginx-external
        enabled: true
        default: false
        controllerValue: "k8s.io/external-ingress-nginx"
    
      # -- For backwards compatibility with ingress.class annotation, use ingressClass.
      # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
      ingressClass: nginx-external
    
      service:
        enabled: true
    
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    
        external:
          enabled: true
    
