apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    alertmanager:
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx-internal
        hosts: 
        - alertmanager.pro.eorozco.lifebit.ai
        paths: 
        - /
    grafana:
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx-internal
        hosts: 
        - grafana.pro.eorozco.lifebit.ai
        paths: 
        pathType: Prefix
            backend:
            - path: /
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 3000
    prometheus:
      ingress:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: nginx-internal
        hosts: 
        - prometheus.pro.eorozco.lifebit.ai
        paths: 
        - /

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  values:
    loki:
      ingress:
        enabled: false
        annotations: 
          kubernetes.io/ingress.class: nginx-external
        hosts:
          - host: loki.pro.eorozco.lifebit.ai
            paths: 
              - /