apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux_apps
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/dtrinf/flux_apps
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux_apps
  namespace: apps
spec:
  serviceAccountName: flux_apps
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux_apps
  prune: true
  validation: client
