---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  timeout: 5m0s
  wait: true
  # values:
  #   alertmanager:
  #     enabled: true
  #     config:
  #       ingress:
  #         enabled: true
  #         annotations: 
  #           kubernetes.io/ingress.class: nginx-external
  #         hosts: 
  #         - "alertmanager.eks.pro.eorozco.lifebit.ai"
  #         paths: /
  #   prometheus:
  #     config:
  #       ingress:
  #         enabled: true
  #         annotations: 
  #           kubernetes.io/ingress.class: nginx-external
  #         hosts: 
  #         - "prometheus.eks.pro.eorozco.lifebit.ai"
  #         paths: /
  #   grafana:
  #     config:
  #       ingress:
  #         enabled: true
  #         annotations: 
  #           kubernetes.io/ingress.class: nginx-external
  #         hosts: []
  #         paths: /grafana/
  

