# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kyverno
#   namespace: flux-system
# spec:
#   interval: 720m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/kyverno
#   prune: true
#   wait: true
#   timeout: 10m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kyverno-policies
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: kyverno
#   interval: 15m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/kyverno-policies
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: sealed
#   namespace: flux-system
# spec:
#   interval: 15m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/sealed
#   prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-internal
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/ingress-controller-internal
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-external
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/ingress-controller-external
  prune: true
  timeout: 10m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: chartmuseum
#   namespace: flux-system
# spec:
#   interval: 15m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   serviceAccountName: kustomize-controller
#   path: ./infrastructure/chartmuseum
#   prune: true
#   timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: notifications
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/notifications
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-external
    - name: ingress-internal
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/monitoring
  prune: true
  timeout: 10m