---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: '6.1.6'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
      interval: 1m
  values:
    replicaCount: 2
    #ui:
      #message: "david"
  valuesFrom:
    - kind: Secret
      name: testsecret
      valuesKey: values.yaml

