apiVersion: v1
kind: Secret
metadata:
    name: test_secret
    namespace: podinfo
data:
    password: ENC[AES256_GCM,data:IbPOEw==,iv:RXi5885pvsDgOj1HmV4+zIm3GNn20k8C0/4j1vxeQUg=,tag:TGi/hd+2l9cWRYw6zw1LiQ==,type:str]
    user: ENC[AES256_GCM,data:Piw2lpMt,iv:YjAJ1tmFOHeYUPsDzuHys9VMleXE1k3NiKbxPGqs0rI=,tag:+bF4chSof9XC8kYXY5cGcw==,type:str]
    another: ENC[AES256_GCM,data:N3mH,iv:R9+BDeDvEoOVgNrNqR+NlrPWXrSFAmP/zeyC+e2BlPM=,tag:kHoHO1TjKqOSGLadvo34Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T08:28:33Z"
    mac: ENC[AES256_GCM,data:oE3kr51FU0jdzJyL8tR4+IG57xBTExCUL626QVLVmaIOGnKKJ886AtWhHw11rj6I4ak/Pu+/k8U5dYqhtj71Y1XM37aenXhlCMmXnVgrFdW7gKQGVfjMdbgutzPwHanUpFFHcUMNK5Px9VXohFvZZEEn5MqojxBo5FspB5S7oZE=,iv:Rapz3QQi6t2VPuTA8B0zmli6POBVEdA0o8xJxlocuZ0=,tag:XddYTt6X/bXrroAKkh0hZg==,type:str]
    pgp:
        - created_at: "2022-07-06T15:40:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2arRn2AErx8AQ/9Gm942vol6PcGgcQzls85v68pjuzJwyBlMAQMpEZn37k/
            PnIuDQGfEz37gjQdd5YlOvAMn/G3IagbcJ8s9/7DsubKoa5++/SXx6ii3hD5bTTg
            gM5IJGxX86cmYPJfcnWhcDIwsjPQ50m2H30GFe7H9f+uTlbOsjIKQwH8IUp2Frju
            M79ty6ppKb7Wz0Zz+p3EAOKqGXa1zgSkSvty7JwsQl8QWK7adpyZyqYsWi0v2dVY
            1A3yV7jaQW4o1TC+pqY0YZdD1UGXGQ1hKbAn30B2a3lTL1HXJ8Zr+cdsjfPzxlL8
            x8kcEuJd83GCrdgY6jzSFsVkrCn+IArhFg1im+fyiC75lIwntymiHcXj5LN79Cg/
            ZjDKvGQwnc8lrDq0wQTH9a7y1farA5pzrSZ49QIRv8GYMyB+wc2KVtv9OKgtWxsx
            kfIyoImjLWPo130ZAgGFTq6qG9THPrcrpIdtXE6hlRh5oPDo99ulQYFBSWbZGVZS
            4FgQ5xAmm+xHJvF88M5JGYoXXwOxDgi6dV/9w3vp2L4jZDr2jERkykENVZQvxgbN
            XWOFgYbq598tUbsi4ePNjqmx3tldQHGBdTjvPEnI1XHGEqTbHOqwdm00fLLU+FDm
            DQwD3D75Xxvz+tYcWRSfj+F/5RqvXKgWQX7zbIv8Jv8aNZ611NrVFW7cimV0etrS
            XgEm/cLpPdUT2Dmo7HkGigC8/lTdr8YJ6HpQw6OWu824IHf1lQJ5KXYRiRjX43Oy
            /VFTXy9Z7N9HjXqWo1I2WdUwAZAdkd9dL5iHvGrxVZDW/3MLg5NZMDqNKB1EtRY=
            =kRwk
            -----END PGP MESSAGE-----
          fp: 8613B989B50503317A8888D881647CC9F85E990B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
