---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-internal

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-internal
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.1.4'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-internal
        namespace: ingress-internal
      interval: 100m
  values:
    controller:

      ingressClassResource:
        # -- Name of the ingressClass
        name: nginx-internal
        enabled: true
        default: false
        controllerValue: "k8s.io/internal-ingress-nginx"

      # -- For backwards compatibility with ingress.class annotation, use ingressClass.
      # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
      ingressClass: nginx-internal

      service:
        enabled: true

        external:
          enabled: false

        internal:
          # -- Enables an additional internal load balancer (besides the external one).
          enabled: true
          # -- Annotations are mandatory for the load balancer to come up. Varies with the cloud service.
          annotations: 
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
            service.beta.kubernetes.io/aws-load-balancer-type: "external"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
