apiVersion: v1
kind: Secret
metadata:
    name: slack-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:cRvrE5sSRVX8dtDqErAuYBifsQijIwu1v9sBcnoGycP+kEqQYTTCzSwZPAViUXjmT6oioiRu1kW8HxbtGDEulq7wP3hHYe4LHQMueBBGVYfs6ZMRlokrfqA7tarV1qsJF7HoeRLk0aGaDvit,iv:n/xBJZlmZpsko9o9MvrI9tinHalxRLAyFzanT2OoaLU=,tag:9t/9tsECK3dln8l122ILDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T13:20:16Z"
    mac: ENC[AES256_GCM,data:cx5PAtwPnnPh6iTO11o0CehkY/KzQXzbMXa6By3JIRoiAJ2gSNkeLPqZa3NfaTq4u5ICqjdaOw19ppmlTrei3u7iTCbX2nv71XTOVV2fJBqJ5dNSl69PtxCMFIbyl/sShL2iV7/T11EOuaEOf7NKvxUPJP4oB/LailwVSTnCEpg=,iv:epvXOBcnBdTd2vYTxDIAA9IsCZxZ9KVLowmMYD85u5k=,tag:64NxDX4r8QFfLw/ngoogTw==,type:str]
    pgp:
        - created_at: "2022-07-07T13:20:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2arRn2AErx8AQ//SFQdSYKv4CZdLSNQEDoPHUGGViTgLxRju7wff9r/jXtp
            iVQ5NrmIBTz/CMPaCjMdbKmQDCOIMcaTUHCET0bI/ANLtrWj8bxRMINqYyjsy1ld
            1u1o4IPdWMliJIr8U/lIxscdBhk/fMnQNWoGKZDOzt27II8Vln4uG0RwyIOQ80hz
            7gz/I4nloyiYF/tdt+tU0t56jwNxDrcEcFb5aRNnODdrTCHb3F9oHBuLAl3kp7oz
            ezWUXIXc2rSDFk6LZgFf2z6RJnvwQLzABJkNLSuwVasMN0jToBXc4U2pPW2Z6sk5
            YqRF7bwBLrKgobXrHiG54OY/zccO1/B+QF0mSWlRFxIvXw5fvL1i/LihVfXbySAH
            a3bFx2zEq3+3XA4ovom/J+k/iIiIRqU8xYC9ChlNp8/7qv54NYm4fa2i0MGEdfcB
            0HZE62EVG0ooIeVlnz8phxHfqKPckLCXMadDl5tPz8wKKN1rcxSoggxJWbLNI3Sg
            0i9J3ub0K8gzubmqNavISLrcXUaKUou8D24e35WjV5W2+boMnwV7d+gnAjIfK0Ab
            QK28StTUxtUDYdhaXp8q+T6mpqkWS6L1/s/60QaShhKPT5ZxR6dF1Jv5u5C9vxih
            n2gE9dJrQIhgpS5CLknHINGOMJZnoEpUWDbVfqLN3UCtit40tSmEeUbqkkSL6bDS
            XgFwMmEzowB9ZH2oSKeTpTVegExJG2YVX9L0W/UyHWVQb+tuWXrGdqzLCpeXeK6p
            1bS6OhBHDPEqKvYzQxAOLi/pPUIJiKB/zYdhCuA/Lgp+hkJ2EhvWc2M5i0lpink=
            =lLBH
            -----END PGP MESSAGE-----
          fp: 8613B989B50503317A8888D881647CC9F85E990B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
