---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-apps
  namespace: apps
spec:
  path: ./infra/edu
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg